### Introduction to array

In [1]:
import numpy as np

In [5]:
#initialisation of an array

array_1d = np.array(['a','n','u'])

print(array_1d)

['a' 'n' 'u']


In [6]:
#validating the data type

type(array_1d)

numpy.ndarray

In [7]:
#passing list to the array

list_numbers = [1,2,3,4,5]

array_numbers = np.array(list_numbers)

In [8]:
print(array_numbers)

[1 2 3 4 5]


In [15]:
#multi dimesional array creation

array_zeros = np.zeros((3,4))   #(row,column) 

In [16]:
array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
#filling array with a counter (usinf for and range)

count = 0

for i in range(0,3):
    """for loop for filling rows"""
    for j in range(0,4):
        """for loop for filling columns"""
        array_zeros[i][j] = count
        count += 1

In [20]:
array_zeros

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])